package ru.topbun.domain.entity

enum class StorageKeys {
    IS_OPEN_ENABLED,
    IS_INTER_ENABLED,
    IS_NATIVE_ENABLED,

    APPLOVIN_OPEN,
    APPLOVIN_INTER,
    APPLOVIN_NATIVE,
    APPLOVIN_BANNER,

    YANDEX_OPEN,
    YANDEX_INTER,
    YANDEX_NATIVE,
    YANDEX_BANNER,

    DELAY_INTER,
    CONTENT_AD_TYPE,

}