package ru.topbun.domain.entity

enum class StorageKeys {
    IS_OPEN_ENABLED,
    IS_INTER_ENABLED,
    IS_NATIVE_ENABLED,

    APPLOVIN_OPEN,
    APPLOVIN_INTER,
    APPLOVIN_NATIVE,
    APPLOVIN_BANNER,

    YANDEX_OPEN,
    YANDEX_INTER,
    YANDEX_NATIVE,
    YANDEX_BANNER,

    DELAY_INTER,
    CONTENT_AD_TYPE,
    COUNT_NATIVE_PRELOAD,
    AD_NATIVE_INTERVAL_CONTENT,
    CHANGE_SHOW_OPEN,
    CHANGE_SHOW_INTER,
    CHANGE_SHOW_NATIVE,

}